print("#REYES MEZA ALAN EDUARDO : act- en clase #NOMBRE PRACTICA Y DATOS DE PROGRAMADOR")

print(" ") #ESPACIO PARA AGREGAR LA INFO DE PRACTICA Y PROGRAMADOR

numero1 = float(input("Ingresa el primer número: ")) ## Solicitar el primer número al usuario

numero2 = float(input("Ingresa el segundo número: ")) ## Solicitar el segundo número al usuario

numero3 = float(input("Ingresa el tercer número: ")) ## Solicitar el tercer número al usuario

resultado = numero1 * numero2 * numero3 ## Realizar la multiplicación de los tres números

print(f"La multiplicación de {numero1}, {numero2} y {numero3} es: {resultado}") ## Mostrar el resultado de la multiplicación